#
###################################
# Site wide configuration
####################################
#
title: VnDragon Blogs 
email:
description: A simple and awesome blog theme powered by jekyll.
url: 'kiennguyenbinh.github.io'
keywords: ["blog", "jekyll"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          Asia/Ho_Chi_Minh
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: VnDragon
  avatar: avatar.jpeg
  job: "Senior Backend Developer"
  bio: ""
  email: "kien.marketingonline@gmail.com"
  disqus-shortname:
  twitter: #username
  facebook: #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: kiennguyenbinh
  gitlab: vndragon
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: kiennguyenbinh
  skype: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  500px: #username
  codepen: #username
  reddit: #username
  telegram: VnDragon
